<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\ApplicationUserModel\Dto\" />
    <Folder Include="Entities\CategoryModel\Dto\" />
    <Folder Include="Entities\Customer\Dto\" />
    <Folder Include="Entities\ItemModel\Dto\" />
    <Folder Include="Entities\Stock\Dto\" />
  </ItemGroup>

</Project>
