<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\ApplicationUserModel\Dto\" />
    <Folder Include="Entities\ProductModels\Dto\" />
    <Folder Include="Entities\CustomerModel\Dto\" />
    <Folder Include="Entities\LotModel\Dto\" />
    <Folder Include="Entities\PurchaseModel\Dto\" />
    <Folder Include="Entities\SalesModel\Dto\" />
    <Folder Include="Entities\StockModel\Dto\" />
    <Folder Include="Entities\WarehouseModel\Dto\" />
  </ItemGroup>

</Project>
